name: Spell check commit messages

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: check-spelling/check-spelling@v0.0.22
